### ISSUE TITLE
Load sub-packages on PEMr attach, or on demand via function `run_pemr()`?

### ISSUE THREAD

**Issue by ateucher** [ninoxconsulting/PEMr-backup#2]
Right now, as I've set it up in #1, this package's main purpose is to ensure that the sub-packages are _installed_, by including them as dependencies in the `DESCRIPTION` file in this package. It also provides the function `run_pemr()` which attaches (loads) the sub-packages into the user's environment. Users can either use `run_pemr()` to load everything and/or call `library()` on individual packages when they need them.

We could, like the [tidyverse package](https://github.com/tidyverse/tidyverse/blob/62f32d43e1e0650e4c05632dbfbe06977d1f292f/R/zzz.R#L2), have the sub-packages loaded automatically when they call `library(PEMr)`. This has the advantage of the sub-packages being a bit more in the background and the user has only one `library()` call to make and everything is ready to go. On the other hand, it will load a lot of functions into the user's namespace at once, as well as a lot of dependencies - though I would guess there is a lot of overlap in dependencies between the packages.

@gcperk what do you think?

**Comment by gcperk** [comment]
@ateucher - hmmm. I can see the advantage of making it easy for the user to just load one library(pemr) to call all. I suspect this is the most simple option, but not sure how big the overhead will be for users with the additional packages that are unlikely to be used in a single session. Lets keep it as one load and if it gets too much was can reassess.

**Comment by ateucher** [comment]
Yeah, I lean to encouraging users to only load the packages they need. I think `PEMr` should probably just be responsible for making sure they're all _installed_, but perhaps not load them. When we set up the directory and file structure we can populate the likely places where those `library()` calls should go...

**Comment by ateucher** [comment]
Resolution: populate `library()` calls in template scripts for individual packages
